services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
        - API_HOST=http://backend:${BACKEND_PORT}
        - NODE_ENV=${NODE_ENV:-production}
    container_name: cloudflare-linker-frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    networks:
      - cloudflare-linker-network
    restart: unless-stopped
    environment:
      - PORT=${FRONTEND_PORT}
      - API_HOST=http://backend:${BACKEND_PORT}
      - NODE_ENV=${NODE_ENV:-production}

  backend:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
      args:
        - BACKEND_PORT=${BACKEND_PORT}
    container_name: cloudflare-linker-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    # En environnement de développement, montez les fichiers pour hot-reload
    # Pour la production, commentez cette ligne pour utiliser les fichiers copiés dans l'image
    # volumes:
    #   - ./fastapi:/app
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - API_V1_STR=${API_V1_STR}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - ALGORITHM=${ALGORITHM}
      - PORT=${BACKEND_PORT}
    networks:
      - cloudflare-linker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload

networks:
  cloudflare-linker-network:
    driver: bridge

volumes:
  db-data:
    driver: local 