version: '3.8'

services:
  backend:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
      args:
        - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./fastapi:/app
      - /app/venv
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - API_V1_STR=${API_V1_STR}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - ALGORITHM=${ALGORITHM}
      - PORT=${BACKEND_PORT}
    command: uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - PORT=${FRONTEND_PORT}
    depends_on:
      - backend 